// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyvgmkkzqmlweodetqvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55dmdta2t6cW1sd2VvZGV0cXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MTMyNDUsImV4cCI6MjA3NTQ4OTI0NX0.033xhzBqiZEpKGwZaH__xOcIBguK8ZfHVxUysNrt7vw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});